const STORYBOOK_URL = "https://figma.github.io/sds/storybook/?path=/story/";

// prettier-ignore
export const devResources = {
  "<FIGMA_CARDS_CARD>": [{ name: "Card - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-card`}],
  "<FIGMA_CARDS_PRICING_CARD>": [{ name: "PricingCard - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-card` }],
  "<FIGMA_CARDS_PRODUCT_INFO_CARD>": [{ name: "ProductInfoCard - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-pricing-card` }],
  "<FIGMA_CARDS_REVIEW_CARD>": [{ name: "ReviewCard - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-review-card` }],
  "<FIGMA_CARDS_STATS_CARD>": [{ name: "StatsCard - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-stats-card` }],
  "<FIGMA_CARDS_TESTIMONIAL_CARD>": [{ name: "TestimonialCard - Storybook", url: `${STORYBOOK_URL}sds-compositions-cards--story-testimonical-card` }],
  "<FIGMA_FORMS_FORM_CONTACT>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_FORMS_FORM_FORGOT_PASSWORD>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_FORMS_FORM_LOG_IN>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_FORMS_FORM_NEWSLETTER>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_FORMS_FORM_REGISTER>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_FORMS_FORM_SHIPPING>": [{ name: "FormBox - Storybook", url: `${STORYBOOK_URL}sds-compositions-forms--story-form-box`}],
  "<FIGMA_SECTIONS_CARD_GRID_CONTENT_LIST>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_CARD_GRID_ICON>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_CARD_GRID_IMAGE>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_CARD_GRID_PRICING>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_CARD_GRID_REVIEWS>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_CARD_GRID_TESTIMONIALS>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_FOOTER>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HEADER_AUTH>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HEADER>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HERO_ACTIONS>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HERO_BASIC>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HERO_FORM>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HERO_IMAGE>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_HERO_NEWSLETTER>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PAGE_ACCORDION>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PAGE_NEWSLETTER>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PAGE_PRODUCT_RESULTS>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PAGE_PRODUCT>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PANEL_IMAGE_CONTENT_REVERSE>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PANEL_IMAGE_CONTENT>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PANEL_IMAGE_DOUBLE>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_SECTIONS_PANEL_IMAGE>": [{ name: "Flex - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-flex`}, { name: "Section - Storybook", url: `${STORYBOOK_URL}sds-layout-section--story-section`}],
  "<FIGMA_ACCORDION_ACCORDION>": [{ name: "Accordion - Storybook", url: `${STORYBOOK_URL}sds-primitives-accordion--story-accordion` }],
  "<FIGMA_ACCORDION_ACCORDION_ITEM>": [{ name: "AccordionItem - Storybook", url: `${STORYBOOK_URL}sds-primitives-accordion--story-accordion-item` }],
  "<FIGMA_AVATARS_AVATAR>": [{ name: "Avatar - Storybook", url: `${STORYBOOK_URL}sds-primitives-avatars--story-avatar`}, { name: "AvatarButton - Storybook", url: `${STORYBOOK_URL}sds-primitives-avatars--story-avatar-button`}],
  "<FIGMA_AVATARS_AVATAR_BLOCK>": [{ name: "AvatarBlock - Storybook", url: `${STORYBOOK_URL}sds-primitives-avatars--story-avatar-block`}],
  "<FIGMA_AVATARS_AVATAR_GROUP>": [{ name: "AvatarGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-avatars--story-avatar-group`}],
  "<FIGMA_BUTTONS_BUTTON>": [{ name: "Button - Storybook", url: `${STORYBOOK_URL}sds-primitives-buttons--story-destructive-button`}],
  "<FIGMA_BUTTONS_BUTTON_DANGER>": [{ name: "ButtonDanger - Storybook", url: `${STORYBOOK_URL}sds-primitives-buttons--story-button-danger`}],
  "<FIGMA_BUTTONS_BUTTON_GROUP>": [{ name: "ButtonGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-buttons--story-button-group`}],
  "<FIGMA_BUTTONS_ICON_BUTTON>": [{ name: "IconButton - Storybook", url: `${STORYBOOK_URL}sds-primitives-buttons--story-icon-button`}],
  "<FIGMA_DIALOG_DIALOG_BODY>": [{ name: "Dialog - Storybook", url: `${STORYBOOK_URL}sds-primitives-dialog--story-dialog`}],
  "<FIGMA_INPUTS_CHECKBOX_FIELD>": [{ name: "CheckboxField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-checkbox-field`}],
  "<FIGMA_INPUTS_CHECKBOX_GROUP>": [{ name: "CheckboxGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-checkbox-group`}],
  "<FIGMA_INPUTS_INPUT_FIELD>": [{ name: "InputField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-input-field`}],
  "<FIGMA_INPUTS_RADIO_FIELD>": [{ name: "RadioField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-radio-field`}],
  "<FIGMA_INPUTS_RADIO_GROUP>": [{ name: "RadioGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-radio-group`}],
  "<FIGMA_INPUTS_SEARCH>": [{ name: "Search - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-search`}],
  "<FIGMA_INPUTS_SELECT_FIELD>": [{ name: "SelectField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-select-field`}],
  "<FIGMA_INPUTS_SLIDER_FIELD>": [{ name: "SliderField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-slider-field`}],
  "<FIGMA_INPUTS_SWITCH_FIELD>": [{ name: "SwitchField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-switch-field`}],
  "<FIGMA_INPUTS_TEXTAREA_FIELD>": [{ name: "TextareaField - Storybook", url: `${STORYBOOK_URL}sds-primitives-inputs--story-textarea-field`}],
  "<FIGMA_MENU_MENU>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_MENU_MENU_HEADER>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_MENU_MENU_HEADING>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_MENU_MENU_ITEM>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_MENU_MENU_SEPARATOR>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_MENU_MENU_SHORTCUT>": [{ name: "Menu - Storybook", url: `${STORYBOOK_URL}sds-primitives-menu--story-menu`}],
  "<FIGMA_NAVIGATION_NAVIGATION_BUTTON_LIST>": [{ name: "NavigationButton - Storybook", url: `${STORYBOOK_URL}sds-primitives-navigation--story-navigation-button`}],
  "<FIGMA_NAVIGATION_NAVIGATION_BUTTON>": [{ name: "NavigationButton - Storybook", url: `${STORYBOOK_URL}sds-primitives-navigation--story-navigation-button`}],
  "<FIGMA_NAVIGATION_NAVIGATION_PILL_LIST>": [{ name: "NavigationPill - Storybook", url: `${STORYBOOK_URL}sds-primitives-navigation--story-navigation-pill`}],
  "<FIGMA_NAVIGATION_NAVIGATION_PILL>": [{ name: "NavigationPill - Storybook", url: `${STORYBOOK_URL}sds-primitives-navigation--story-navigation-pill`}],
  "<FIGMA_NOTIFICATION_NOTIFICATION>": [{ name: "Notification - Storybook", url: `${STORYBOOK_URL}sds-primitives-notification--story-notification`}],
  "<FIGMA_PAGINATION_PAGINATION_GAP>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_PAGINATION_PAGINATION_LIST>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_PAGINATION_PAGINATION_NEXT>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_PAGINATION_PAGINATION_PAGE>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_PAGINATION_PAGINATION_PREVIOUS>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_PAGINATION_PAGINATION>": [{ name: "Pagination - Storybook", url: `${STORYBOOK_URL}sds-primitives-pagination--story-pagination`}],
  "<FIGMA_TABS_TAB>": [{ name: "Tabs - Storybook", url: `${STORYBOOK_URL}sds-primitives-tabs--story-tabs`}],
  "<FIGMA_TABS_TABS>": [{ name: "Tabs - Storybook", url: `${STORYBOOK_URL}sds-primitives-tabs--story-tabs`}],
  "<FIGMA_TAGS_TAG>": [{ name: "Tag - Storybook", url: `${STORYBOOK_URL}sds-primitives-tags--story-tag`}, { name: "TagButton - Storybook", url: `${STORYBOOK_URL}sds-primitives-tags--story-tag-button`}],
  "<FIGMA_TAGS_TAG_TOGGLE>": [{ name: "TagToggleGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-tags--story-tag-toggle-group`}],
  "<FIGMA_TAGS_TAG_TOGGLE_GROUP>": [{ name: "TagToggleGroup - Storybook", url: `${STORYBOOK_URL}sds-primitives-tags--story-tag-toggle-group`}],
  "<FIGMA_TEXT_TEXT_CODE>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_CONTENT_HEADING>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_CONTENT_TITLE>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_EMPHASIS>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_HEADING>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_LINK_LIST_ITEM>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_LINK_LIST>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_LINK>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_LIST_ITEM>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_LIST>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_PRICE>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_SMALL>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_STRONG>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_SUBHEADING>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_SUBTITLE>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_TITLE_HERO>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT_TITLE_PAGE>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TEXT_TEXT>": [{ name: "Text - Storybook", url: `${STORYBOOK_URL}sds-primitives-text--story-text`}],
  "<FIGMA_TOOLTIP_TOOLTIP>": [{ name: "Tooltip - Storybook", url: `${STORYBOOK_URL}sds-primitives-tooltip--story-tooltip`}],
};
